config/routes.rb
Rails.application.routes.draw do
  

  devise_for :user
  resources :comments
  resources :posts

  root 'posts#index'

# User's Posts
  get '/:name' => 'posts#user_posts', as: :user_posts

#get = retrieve info / data
  get 'index' => 'practice#index'
  
  get 'about' => 'practice#about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  #Associations

  belongs_to :user
  has_many :comments

  #Pagination with Kaminari
  
  paginates_per 3  
end

app/models/user.rb
class User < ActiveRecord::Base

   has_many :posts
   has_many :comments
         
  mount_uploader :avatar, AvatarUploader
 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 
  # User Avatar Validation
  # validates_integrity_of  :avatar
  # validates_processing_of :avatar
 
  private
    def avatar_size_validation
      errors[:avatar] << "should be less than 500KB" if avatar.size > 0.5.megabytes
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :avatar])

    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :avatar])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_path(id: @comment.post_id), notice: 'Dope! Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:author, :comment_entry, :post_id, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

# Show all users posts

  def user_posts
    @user = User.find_by(username: params[:name])
  end

  #file continues with index action

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order(:created_at).reverse_order.page(params[:page])
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :author, :blog_entry, :user_id)
    end
end

app/controllers/practice_controller.rb
class PracticeController < ApplicationController
  
  def index
    @name = params[:name]
  end

  def about
    @color = params[:color]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/practice_helper.rb
module PracticeHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<!-- COMMENT AUTHOR / USER_ID AS VALUE -->
  <div class="form-group">
    <p><%= form.hidden_field :user_id, value: current_user.id %>
  </div>
<!-- COMMENT ENTRY -->
  <div class="form-group">
    <%= form.text_area :comment_entry, class: "form-control" %>
  </div>
<!-- HIDDEN POST ID -->
  <div class="form-group">
     <%= form.hidden_field :post_id, value: @post.id %>
  </div>
<!-- SUBMIT COMMENT -->
  <div class="form-group">
    <%= form.submit "Submit", class: "btn btn-in" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Comment entry</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.author %></td>
        <td><%= comment.comment_entry %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @comment.author %>
</p>

<p>
  <strong>Comment entry:</strong>
  <%= @comment.comment_entry %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechTalentBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">

      <head>
    <title>SspPrototype</title>
    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>

<body>
<!-- HEADER -->
  <header class="navbar  navbar-inverse">
    <div class="navbar-class">
      <!-- Collect the nav links, forms, and other content for toggling -->
        <ul class="nav navbar-nav">
          <li class="active">
            <li><%=link_to "Home", root_path %></li>
            <li><%=link_to "Blog Posts", posts_path %></li>
            <li><%=link_to "Comments", comments_path %></li>
              <div class="pull-right">
                <% if current_user.avatar.url != nil %>
                  <%= image_tag current_user.avatar.url, class: "avatar" %> 
             <!-- EDIT USER -->
                  <% end %> 
                <%= link_to "Edit Profile",
             edit_user_registration_path, class: "btn btn-primary btn-sm" %> 
              <!-- SIGNOUT BUTTON -->

                  <%= link_to "Sign Out", destroy_user_session_path, method: :delete, 
                  :id=> "sign_out", class:  "btn btn-sml btn-info" %>  
              </div>

              <!-- end of SIGN OUT -->
         </li>  
    </div>
  </ul>
 </header>
<!-- END OF HEADER -->


</body>
      <!-- NAV goes here -->
      <%= yield %>
      <!-- Footer goes here -->
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<!-- BLOG TITLE -->
  <div class="form-group">
    <%= form.text_field :title, placeholder: "Blog Title", class: "form-control" %>
  </div>
<!-- BLOG AUTHOR / USER ID AS VALUE-->
  <div class="form-group">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>
<!-- BLOG ENTRY -->
  <div class="form-group">
    <%= form.text_area :blog_entry, placeholder: "Blog Entry", class: "form-control" %>
  </div>

<!-- SUBMIT BUTTN -->
  <div class="actions">
    <%= form.submit "Submit", class: "btn btn-info btn-lg" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-3">Garrett N Thoughts</h1>
    <p class="lead">WARNING: Turn back now, or else...</p>
  </div>
</div>

<p class="btn btn-info btn-small"><%= link_to 'New Post', new_post_path %></p>
<!-- Content -->
<div class="masonary-row row">
  <div class="posts">
    <!-- Iteration -->
    <% @posts.each do |post| %>
    <!-- Columns -->
      <div class="col-md-6">
        <!-- Panels -->
        <div class="panel panel-success">
          <div class="panel-heading">
             <h3><%= post.title %></h3>
             <!-- Username / time / link_to user post -->
             <h4>By: <%= link_to post.user.username, user_posts_path(name: post.user.username) %>, <%= post.created_at.strftime("%A %m/%d/%y") %></h4>
             <!-- Avatar Validation -->
              <% if post.user.avatar.url != nil %>
              <%= image_tag current_user.avatar.url, class: "avatar pull-right"%>
          <% end %>
           </div>
           <!-- Blog Entry / Panel Body -->
          <div class="panel-body">
            <p>
              <strong>Blog Entry:</strong>
             <%= post.blog_entry.html_safe %>
            </p>
          </div>       
          <div class="panel-footer">
            <!-- Buttons -->
            <p class="btn btn-primary btn-small"><%= link_to 'Show', post %></p>
            <p class="btn btn-info btn-small"><%= link_to 'Edit', edit_post_path(post) %></p>
            <p class="btn btn-warning btn-small"><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
            </p>
          </div>
        </div>
      </div>
   <% end %>
  </div>
</div>


<!-- Pagination of Pages Kaminari -->
<%= paginate @posts %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-success">
  <div class="panel-heading">
    <p>
      <strong>Title:</strong>
      <%= @post.title %>
    </p>
<!-- AUTHOR -->
  <p><strong>By:</strong> <%= link_to @post.user.username, user_posts_path(name: @post.user.username) %>, <%= @post.created_at.strftime("%A %m/%d/%y") %></p>
  </div>
  <div class="panel-body">

    <p>
      <strong>Blog entry:</strong>
      <%= @post.blog_entry.html_safe %>
    </p>


      <div id = "comments" class="well">
        <!-- Display Comments Form Partial -->
        <%= render 'comments/form', comment: @comment %>
        
        <!-- Comments Iteration -->
        <% @post.comments.each do |comment| %>
          <div class="panel panel-info">
            <div class="panel-heading">
              <!-- Show Author & link to user_posts -->
              <p><%= link_to comment.user.username, user_posts_path(name: comment.user.username) %></p>
            </div>
            <div class="panel-body">
              <p><%= comment.comment_entry %></p>
            </div>
          </div>
        <% end %>
        <!-- End Comments -->

      </div>
  </div>
</div>
<!-- Buttons -->
  <p class="btn btn-info btn-small"><%= link_to 'Edit', edit_post_path(@post)%> </p>
  <p class="btn btn-warning btn-small"><%= link_to 'Back', posts_path %></p>

app/views/posts/user_posts.html.erb
<!-- Header calling Username -->
<h1>All Posts by <%= @user.username %> </h1>
<!-- Iterate Thru user's posts -->
<% @user.posts.each do |post| %>
  <div class="row">
    <div class="col-md-8 col-offset-2">
      <div class="well">
    <!-- Content of each User's post-->
        <h3><%= post.title %></h3>
        <!-- Style the time of post -->
        <p><em>posted on <%= post.created_at.strftime("%a/%m/%d/%y") %></em></p>
        <!-- Blog Entry with HTML Safe attributes -->
        <p><%= post.blog_entry.html_safe %> </p>
        <!-- Links Links Links -->
        <p>
          <!-- Link to individual Post -->
          <%= link_to "Show", post, class: "btn btn-danger btn-sm" %> 
          <!-- Check to see if current User owns post -->
          <% if current_user.id == post.user_id %> 
            <!-- EDIT and DESTROY if User owns post -->
            <%= link_to "Edit", edit_post_path(post), class: "btn btn-info btn-sm" %> 
            <%= link_to "Destroy", post, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger btn-sm" %> 
          <% end %> 
        </p>
      </div>
    </div>
  </div>
<% end %>  

app/views/practice/about.html.erb
<style type="text/css">
  #color_me_in {
    background-color: <%= @color %>;
    color: white;
    width: 250px;
    height: 250px;
  }
</style>




<div id = "color_me_in">

    <p>
      <%= @color.upcase %> BOX ACTIVATED! 
    </p>

    <p>  
      <%= link_to "Home", index_path %>
    </p>

</div>

<%= form_tag index_path do %>


  <p><%= text_field_tag :name, nil, placeholder:"What is your name?" %> </p>
  <p><%= submit_tag :submit %> </p> 

<% end %>

<h1>SWEET</h1>

app/views/practice/index.html.erb
<!-- Index.html.erb -->
<h1>Choose a Color!</h1>
<!-- Condition - if name is not blank, throw out <h2>info -->
<% if !@name.blank?  %>

  <h2>Welcome Back, <%= @name %> </h2>

<% end %>


<p>
  <%= link_to "Red", about_path(color: "red") %>  <!-- link_to instead of href -->
</p>
<p>
  <%= link_to "Blue", about_path(color: "blue") %>   
</p>
<p>
  <%= link_to "Green", about_path(color: "green") %> 
</p>
<p>
  <%= link_to "Yellow", about_path(color: "yellow") %> 
</p>